name: Thesis2020
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - jupyterlab
  - numpy
  - matplotlib
  - pylatexenc
  - pandas
  - pip:
    - igraph
    - qiskit>=0.23.0
    - pycairo