name: Thesis2020
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy
  - matplotlib
  - pylatexenc
  - pandas
  - pip:
    - python-igraph>=0.9.6
    - qiskit>=0.23.0
    - pycairo